packages:
  - '.'
allowBuilds:
  '@carbon/icon-helpers': set this to true or false
  '@carbon/icons-react': set this to true or false
  '@tailwindcss/oxide': set this to true or false
  esbuild: set this to true or false
onlyBuiltDependencies:
  - '@carbon/icon-helpers'
  - '@carbon/icons-react'
  - '@tailwindcss/oxide'
  - esbuild
