/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS
 *
 * Supabase project credentials. These are read from Vite env vars so the
 * secrets are never committed to source. Configure them in `.env.local`:
 *
 *   VITE_SUPABASE_PROJECT_ID=lhamzfmrbxzqpwkxwyah
 *   VITE_SUPABASE_ANON_KEY=eyJhbGciOi...
 *
 * The anon key is safe to expose to the browser (it is gated by RLS), but
 * the project id / URL and key should still come from the environment so
 * they can be rotated without code changes.
 */

function required(name: string): string {
  const value = import.meta.env[name] as string | undefined;
  if (!value) {
    throw new Error(
      `[supabase] Missing required env var ${name}. Copy .env.example to .env.local and fill it in.`,
    );
  }
  return value;
}

export const projectId = required("VITE_SUPABASE_PROJECT_ID");
export const publicAnonKey = required("VITE_SUPABASE_ANON_KEY");
